### ISSUE TITLE
How to set a marker in the center of the map?

### ISSUE THREAD

**Issue by jojo12** [astridx/magazin#1]
How can I set a marker in the center of the map?

**Comment by jojo12** [comment]
I found a solution. I replaced in coordstomap.php line 54 with
`		$replacement = '<a href="http://www.openstreetmap.org/?mlat=$1&mlon=$2&zoom=15&layers=M">$1 $2</a>';`

[By the way: I know, you made this example to show how to create a joomla plugin. But your example is nice to use it like that. 1000 thanks!

**Comment by astridx** [comment]
@jojo12 OK. Thank you for charing your solution.
