### ISSUE TITLE
negative coordinates don't work!

### ISSUE THREAD

**Issue by jojo12** [astridx/magazin#2]
Sorry, your interest were to show how to create a plugin. 
But I need your example to use openstreetmap in joomla.
It works with positive numbers, but now I tried with negative numbers. 
This doesn't work.
I am not so experienced, perhaps you can help me (and perhaps others too)
thanks.

**Comment by jojo12** [comment]
I tried with changing the line 48 to
`$pattern = "/(-[0-9.]+) (-[0-9.]+)/";`
then it works, when both expressions are negative
`$pattern = "/(-[0-9.]+) ([0-9.]+)/";`
then it works, when only the first number is negative
`$pattern = "/([0-9.]+) (-[0-9.]+)/";`
then it works, when only the second number is negative

but now, how to do, that it works in any case?

**Comment by astridx** [comment]
What exactly does not work?

**Comment by jojo12** [comment]
Hi, 
there will be only the numbers (coordinates) in the article, 

I found a solution, it needs:
`			$pattern = "/(-?[0-9.]+) (-?[0-9.]+)/";`
with that the maps are shown, even with negative coordinates (for the south and/or the west)

**Comment by astridx** [comment]
Ok, fine. Then I close this issue.
